name:                day17
version:             0.1.0.0
github:              "obreitwi/day17"
license:             BSD-3-Clause
author:              "Oliver Breitwieser"
maintainer:          "oliver@breitwieser.eu"
copyright:           "MIT"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            value

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/obreitwi/day17#readme>

dependencies:
- base >= 4.7 && < 5
- attoparsec >= 0.14.4
- containers >= 0.4.0.0
- text >= 2.0.2
- vector >= 0.13.1.0
- rebase >= 1.19
- data-memocombinators >= 0.5.1

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  day17-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day17

tests:
  day17-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day17
